KS-1-5 28.03.2023 Объявил переменную, вывел на экран.
SaNchello86/KotlinSprint pull request #6
Opened 2023-03-28 19:43 UTC by SaNchello86

Объявил переменную, вывел на экран.

2023-03-29 07:40 UTC, ievetrov requested changes

2023-03-29 07:40 UTC, ievetrov commented on src/main/kotlin/lession_1/lession_1_task_5.kt
> +        println("Время проведённое в космосе - " + second + ":00")
тут что то с отступом случилось.

2023-03-29 07:40 UTC, ievetrov commented on src/main/kotlin/lession_1/lession_1_task_5.kt
> +        println("Время проведённое в космосе - " + second + ":00")
Формат вывода был описан как
> минуты:секунды

Будь внимательнее к требованиям.
В реальных проектах, даже если тебе кажется что правильно по-твоему, лучше сделать как в требованиях.
В идеале, кончено, на этапе получения задачки от заказчика нужно уточнить корректность, но в нашем случае необязательно, так как ошибки нам только на пользу.

2023-03-30 15:14 UTC, SaNchello86 commented on src/main/kotlin/lession_1/lession_1_task_5.kt
> +        println("Время проведённое в космосе - " + second + ":00")
Есть некоторое недопонимание как выводить временные отрезки

2023-03-31 06:11 UTC, ievetrov requested changes

2023-03-31 06:11 UTC, ievetrov commented on src/main/kotlin/lession_1/lession_1_task_5.kt
> +    var secondYG = 6480/60
на этой строке 3 момента:
1. форматирование - по код стайлу между оператором должен быть пробел (как в предыдущем коммите было)
2. мы всегда изначально пишем неизменяемые переменные val. и только если того требует программа пишутся изменяемые var. в данном случае ты нигде не перезаписываешь secondYG. то есть она остается неизменяемой
3. ну и нейминг, просто обращаю внимание. что лучше называть переменные конкретно для чего они нужны и что в себе несут. если кто то видит код в первый раз, сразу чтобы сориентировался. тут на мой взгляд уместнее было бы что-то вроде secondsInSpace для 6480. ну и далее по такому принципу

2023-03-31 06:11 UTC, ievetrov commented on src/main/kotlin/lession_1/lession_1_task_5.kt
> +    val result = secondYG-60
на этой строке тоже недостаток пробелов вокруг оператора минус

2023-03-31 06:11 UTC, ievetrov commented on src/main/kotlin/lession_1/lession_1_task_5.kt
> +        println("Время проведённое в космосе Юрием Гагариным: - " + result + ":00")
на этой строке лишний отступ слева.
и что я имел в виду насчет более правильного вывода. в условии указано "в формате [минуты:секунды], например так: 01:09". это значит, что надо вывести только данные в таком виде. без дополнительного аннотационного текста.

2023-04-06 18:34 UTC, SaNchello86 commented on src/main/kotlin/lession_1/lession_1_task_5.kt
> +        println("Время проведённое в космосе Юрием Гагариным: - " + result + ":00")
Иван добрый вечер! переименовал через Refactor имя файла и теперь не могу откомитеть изменения в Git.

2023-04-07 06:51 UTC, closed without merging

2023-04-07 08:16 UTC, SaNchello86 commented
https://github.com/SaNchello86/KotlinSprint/pull/8

2023-04-07 08:34 UTC, ievetrov commented
вижу что этот пулл реквест закрыт, поэтому пришли пожалуйста в бот ссылку на актуальное решение